### ISSUE TITLE
Can't access conversations

### ISSUE THREAD

**Issue by williammb1** [devguilhermy/botpress-inbox#5]
Hi there, new to node so not sure if I'm missing something on my end. 

I have created a .env file under botpress inbox, added the information and run the code, however when I open it in browser it says it could not load previous conversations. 

Any help here would be greatly appreciated. 

Thanks.
<img width="1300" alt="Screenshot 2023-08-10 at 11 41 50 AM" src="https://github.com/devguilhermy/botpress-inbox/assets/141883647/b7fc0794-4c5c-40ae-b8f5-a0b1b258b65a">

**Comment by huznot** [comment]
I was having the same problem, heres what i did and worked. put your .env file not inside botpress-user-test (i changed the name of it) and not inside "botress-inbox-main". also your bot id, worskspace id, etc should not be in quotation marks and the ids should just be pasted in plain text with no spaces. Rerun the server and it should work
![image](https://github.com/devguilhermy/botpress-inbox/assets/126637445/101c1e20-9433-4548-b6f3-99b31376228f)

**Comment by williammb1** [comment]
Thanks for reaching out, appreciate it.

Sorry, did you create a new folder called botpress-user-test and then add
everything into it?

Also for: VITE_BOTPRESS_BOT_ID_AS_USER=<your bot id as a user> should I
just leave it as is or remove the <your id as a user>

Forgive me I am very new to all this.

Thanks again!
Will

**Comment by huznot** [comment]
All good. What i did was download this folder and then extracted the zip folder that was downloaded. When i opened the extracted folder in vs code, it already had a folder inside of it called "botpress-inbox-main" (i dont remember the exact name of  it so i might be wrong) but i changed the name to botpress-user-test because of some error with running npm on that name, i forgot the exact error too 😂. Im assuming you do not have that folder inside the root folder and if thats the case then you can just make a folder and call it whatever you want it doesnt matter but to guide you step by step, lets just say you named it botpress-user-test

so now what your gonna do is all the other files and folder to that folder. Then add that .env file to botpress-user-test and now your files should look like mine in the screenshot i sent earlier

Now, in the .env file, your bot id and everything should not be in quotation marks, like shown in the screenshot attached
![image](https://github.com/devguilhermy/botpress-inbox/assets/126637445/9590acf4-4ec6-4ff6-8659-59f67c2677a8)

For VITE_BOTPRESS_BOT_ID_AS_USER, im not exactly sure what that means or what its supposed to do so i just skipped that part in the instructions, I wouldn't delete it because that might raise undefined errors in the code so just leave it be and it doesnt really do anything. I think its to be able to send messages as the bot from here but I didnt really need that so i just ignored it.

Now this is an important part when running this folder, When you run this folder; make sure in your terminal that you are inside the botpress-user-test folder or whatever you named it and you can do that by running the following command in the terminal, `cd .\botpress-user-test\` .  Now your terminal should look like this.
![image](https://github.com/devguilhermy/botpress-inbox/assets/126637445/653dd06d-c0a1-4300-bb8f-017c9d6a31b6)

After this, do not use `npm install && npm run dev` to run the server, it doesnt work. First run `npm install` and then run `npm run dev`

It should now run the server and give you a link so just open it and everything should be loaded

Sorry for all the things i forgot, its been a while since i did this. If you have any other questions, feel free to ask. Good Luck !

**Comment by williammb1** [comment]
Your a legend, thanks so much for all the help, really appreciate it!!On 21/08/2023, at 2:46 PM, huznot ***@***.***> wrote:﻿
All good. What i did was download this folder and then extracted the zip folder that was downloaded. When i opened the extracted folder in vs code, it already had a folder inside of it called "botpress-inbox-main" (i dont remember the exact name of  it so i might be wrong) but i changed the name to botpress-user-test because of some error with running npm on that name, i forgot the exact error too 😂. Im assuming you do not have that folder inside the root folder and if thats the case then you can just make a folder and call it whatever you want it doesnt matter but to guide you step by step, lets just say you named it botpress-user-test
so now what your gonna do is all the other files and folder to that folder. Then add that .env file to botpress-user-test and now your files should look like mine in the screenshot i sent earlier
Now, in the .env file, your bot id and everything should not be in quotation marks, like shown in the screenshot attached

For VITE_BOTPRESS_BOT_ID_AS_USER, im not exactly sure what that means or what its supposed to do so i just skipped that part in the instructions, I wouldn't delete it because that might raise undefined errors in the code so just leave it be and it doesnt really do anything. I think its to be able to send messages as the bot from here but I didnt really need that so i just ignored it.
Now this is an important part when running this folder, When you run this folder; make sure in your terminal that you are inside the botpress-user-test folder or whatever you named it and you can do that by running the following command in the terminal, cd .\botpress-user-test\ .  Now your terminal should look like this.

After this, do not use npm install && npm run dev to run the server, it doesnt work. First run npm install and then run npm run dev
It should now run the server and give you a link so just open it and everything should be loaded
Sorry for all the things i forgot, its been a while since i did this. If you have any other questions, feel free to ask. Good Luck !

**Comment by devguilhermy** [comment]
Hey guys!
Sorry for the delayed response @williammb1, and thanks a lot for the help @huznot!!

I released a new version that doesn't require you to write variables in files, after running the app it will ask for your token and ids (saved locally) and then it will just work!

The nested folder happens because Github creates a separate folder for each branch of the repository, in this case we have only main, so it creates the folders `botpress-inbox/botpress-inbox-main`, but you can move and rename the botpress-inbox-main as you like!
